---
# - name: Install genieacs
#   sudo: yes
#   npm: name=genieacs global=yes state=present

- name: Install genieacs with git clone
  git: repo=https://github.com/Kalagan/genieacs.git dest={{genieacsDir}} version=07f4f8d6f5312399b1d8288f17f59fc9dd7ac5e7
  register: genieacs_cloned

- name: install node-gyp
  command: npm install -g node-gyp
  sudo: yes
  when: genieacs_cloned|changed

- name: install hiredis
  command: npm install hiredis@0.1.17 chdir={{genieacsDir}}
  when: genieacs_cloned|changed

# - name: node-gyp rebuild
#   command: node-gyp rebuild chdir={{genieacsDir}}
#   sudo: yes
#   ignore_errors: yes
#   when: genieacs_cloned|changed

- name: sudo npm install
  command: npm install chdir={{genieacsDir}}
  sudo: yes
  when: genieacs_cloned|changed

- name: npm install
  command: npm install chdir={{genieacsDir}}
  when: genieacs_cloned|changed

# - name: run npm Install
#   npm: path={{genieacsDir}}
#   sudo: yes
#   when: genieacs_cloned|changed

- name: "Check list of Node.js apps running."
  command: forever list
  register: forever_list
  changed_when: false

- name: "Start genieacs-cwmp"
  command: forever --uid "genieacs-cwmp" -al /var/log/genieacs-cwmp.log start {{genieacsDir}}/bin/genieacs-cwmp
  when: "forever_list.stdout.find('genieacs-cwmp') == -1 or genieacs_cloned|changed"

- name: "Start genieacs-nbi"
  command: forever --uid "genieacs-nbi" -al /var/log/genieacs-nbi.log start {{genieacsDir}}/bin/genieacs-nbi
  when: "forever_list.stdout.find('genieacs-nbi') == -1 or genieacs_cloned|changed"

- name: "Start genieacs-fs"
  command: forever --uid "genieacs-fs" -al /var/log/genieacs-fs.log start {{genieacsDir}}/bin/genieacs-fs
  when: "forever_list.stdout.find('genieacs-fs') == -1 or genieacs_cloned|changed"


- name: add genieacs-cwmp to the boot process
  lineinfile: dest={{homeFolder}}/startup.sh line="forever --uid "genieacs-cwmp" -al /var/log/genieacs-cwmp.log start {{genieacsDir}}/bin/genieacs-cwmp"

- name: add genieacs-nbi to the boot process
  lineinfile: dest={{homeFolder}}/startup.sh line="forever --uid "genieacs-nbi" -al /var/log/genieacs-nbi.log start {{genieacsDir}}/bin/genieacs-nbi"

- name: add genieacs-fs to the boot process
  lineinfile: dest={{homeFolder}}/startup.sh line="forever --uid "genieacs-fs" -al /var/log/genieacs-fs.log start {{genieacsDir}}/bin/genieacs-fs"

- include: nginx_config.yml
