---
- hosts: all
  remote_user: atscom
  vars_files:
    - vars/defaults.yml
  roles:
    - common
    - nodejs
    - node-forever
    - redis
    - nginx
    - ruby
  environment:
    https_proxy: http://vis:visiteur@www-cache.aql.fr:3128
    http_proxy: http://vis:visiteur@www-cache.aql.fr:3128

