---
# this one needs to be run before runing the deploy via capistrano
- hosts: syncserver
  remote_user: atscom
  vars_files:
    - vars/defaults.yml
  roles:
    - postgres
    - sync-server-pre-deploy
  environment:
    https_proxy: http://vis:visiteur@www-cache.aql.fr:3128
    http_proxy: http://vis:visiteur@www-cache.aql.fr:3128
