---
# this one needs to be run after runing the deploy via capistrano
- hosts: syncserver
  remote_user: atscom
  vars_files:
    - vars/defaults.yml
  roles:
    - certification
    - sync-server
