---
- hosts: tr069
  remote_user: atscom
  vars_files:
    - vars/defaults.yml
  roles:
    - mongodb
    - certification
    - genieacs
    - genieacs-gui
  environment:
    https_proxy: http://vis:visiteur@www-cache.aql.fr:3128
    http_proxy: http://vis:visiteur@www-cache.aql.fr:3128
