---
- name: Install PostgreSQL dependencies
  sudo: yes
  action: apt pkg={{item}} state=present
  with_items:
    - python-pycurl
    - python-psycopg2
  tags:
   - postgres

- name: Add PostgreSQL repo key
  sudo: yes
  apt_key: url=http://apt.postgresql.org/pub/repos/apt/ACCC4CF8.asc
  tags:
   - postgres
  environment:
    https_proxy: http://vis:visiteur@www-cache.aql.fr:3128
    http_proxy: http://vis:visiteur@www-cache.aql.fr:3128

- name: Add PostgreSQL repo
  sudo: yes
  apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main'
  tags:
   - postgres

- name: Install postgresql-common
  sudo: yes
  apt: pkg=postgresql-common state=installed update_cache=true
  tags:
   - postgres

- name: Install PostgreSQL
  sudo: yes
  apt: pkg=postgresql-9.3 state=present update_cache=true
  tags:
   - postgres

- name: Install libpq-dev
  sudo: yes
  apt: pkg=libpq-dev state=installed update_cache=true
  tags:
   - postgres

- name: create the postgresql user for syncserver
  postgresql_user: name={{postgresDbUser}} password={{postgresDbPassword}}
  sudo: yes
  sudo_user: postgres
  tags:
   - postgres

- name: create the postgresql database for syncserver
  postgresql_db: name={{postgresDbName}} owner={{postgresDbUser}} state=present
  sudo: yes
  sudo_user: postgres
  tags:
   - postgres
