---
- name: copy nginx config file
  sudo: yes
  template: src=nginx_config.j2 dest=/etc/nginx/sites-available/genieacs-gui
  register: genieacs_gui_ngninx_config_created

- name: enable the website
  sudo: yes
  file: src=/etc/nginx/sites-available/genieacs-gui dest=/etc/nginx/sites-enabled/genieacs-gui state=link

- name: restart nginx
  when: genieacs_gui_ngninx_config_created|changed
  sudo: yes
  action: service name=nginx state=restarted