# README
#
#	before building this image, you need to copy the files from NodeWebSocket to here
# (no need to copy the node_modules folder)
#
# cp ../../../NodeWebSocket/* .
#
# !README

FROM        node:0.10-onbuild

EXPOSE      3051 3052